USE [master]
GO

/****** Object:  Database [onlineSAMart]    Script Date: 2024/08/30 22:38:20 ******/
DROP DATABASE [onlineSAMart]
GO

/****** Object:  Database [onlineSAMart]    Script Date: 2024/08/30 22:38:20 ******/
CREATE DATABASE [onlineSAMart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'onlineSAMart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\onlineSAMart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'onlineSAMart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\onlineSAMart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [onlineSAMart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [onlineSAMart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [onlineSAMart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [onlineSAMart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [onlineSAMart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [onlineSAMart] SET ARITHABORT OFF 
GO

ALTER DATABASE [onlineSAMart] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [onlineSAMart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [onlineSAMart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [onlineSAMart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [onlineSAMart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [onlineSAMart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [onlineSAMart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [onlineSAMart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [onlineSAMart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [onlineSAMart] SET  ENABLE_BROKER 
GO

ALTER DATABASE [onlineSAMart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [onlineSAMart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [onlineSAMart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [onlineSAMart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [onlineSAMart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [onlineSAMart] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [onlineSAMart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [onlineSAMart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [onlineSAMart] SET  MULTI_USER 
GO

ALTER DATABASE [onlineSAMart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [onlineSAMart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [onlineSAMart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [onlineSAMart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [onlineSAMart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [onlineSAMart] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [onlineSAMart] SET QUERY_STORE = ON
GO

ALTER DATABASE [onlineSAMart] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [onlineSAMart] SET  READ_WRITE 
GO

